# Server settings
server:
  port: 8080
  address: 0.0.0.0
# SPRING PROFILES
spring:
  devtools:
    restart:
      enabled: true
      exclude: templates/**
  thymeleaf:
    prefix:
      classpath: /templates/
    mode: LEGACYHTML5
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/travel?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
pagehelper:
  helperDialect: mysql
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: false
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql
logging:
  level:
    com.cn.travel: debug
path: E:/DeskTop/travel/target/

